authors = ["Francesc Rocher"]
name = "aoc_2023_08"
version = "2023.08"
description = "Advent of Code 2023 - Day 8"
licenses = "MIT"

executables = ["part_1", "part_2"]

[build-switches."*"]
ada_version = ["-gnat2022", "-gnatX0", "-gnatW8"]
[[depends-on]]
euler_tools = "^1.3.0"
[[pins]]
euler_tools = { path = '/home/ada/alr/euler_tools' }
