mold-replacement-in-filenames = "true"
mold-overwrite-destination-files = "true"

Author = "Francesc Rocher"
Email = "francesc.rocher@gmail.com"
Address = "{{Author}} <{{Email}}>"
Year = "2023"
Day = "9"
ZDay = "{{Day/pl02}}"
License = "MIT"
