authors = ["Francesc Rocher"]
name = "aoc_2023_07"
version = "2023.07"
description = "Advent of Code 2023 - Day 7"
licenses = "MIT"

executables = ["part_1", "part_2"]

[build-switches."*"]
ada_version = ["-gnat2022", "-gnatX0", "-gnatW8"]
