authors = ["Francesc Rocher"]
name = "aoc_2023_01"
version = "2023.01"
description = "Advent of Code 2023 - Day 1"
licenses = "MIT"

executables = ["part_1", "part_2"]

[build-switches."*"]
ada_version = ["-gnat2022", "-gnatX", "-gnatW8"]
